import moment from 'moment';
export const establishment = {
  en: {
    company: 'Company label',
    year: 'Year Founded',
    firstName: 'First Name',
    lastName: 'Last Name',
    wilaya: 'Wilaya',
    commune: 'Commune',
    phone: 'phone Number',
    link: 'Social Media Link',
    email: 'Email',
    photo: {
      text1: 'Click to upload your Logo',
      text2: 'or drag and drop',
    },
    video: 'add a description Video',
    program: [
      { value: 'my own program', label: 'my own program' },
      { value: 'morchid program', label: 'morchid program' },
      { value: 'medad', label: 'medad' },
      { value: 'el-mitak', label: 'el-mitak' },
      { value: 'mostakbali', label: 'mostakbali' },
      { value: 'my first steps', label: 'my first steps' },
      { value: 'ennahar', label: 'ennahar' },
      { value: 'dar oussama', label: 'dar oussama' },
      { value: 'mentsouri', label: 'mentsouri' },
      { value: 'the little reader', label: 'the little reader' },
      { value: 'Jelis', label: 'Jelis' },
      { value: 'Welcome', label: 'Welcome' },
      { value: 'other', label: 'other' },
    ],
    submit: 'subscribe',
  },
  ar: {
    company: 'اسم الشركة',
    year: 'سنة التأسيس',
    firstName: 'الاسم الاول',
    lastName: 'الاسم الاخير',
    wilaya: 'الولاية',
    commune: 'البلدية',
    phone: 'رقم الهاتف',
    link: 'رابط الصفحة الاجتماعية',
    email: 'البريد الالكتروني',
    photo: {
      text1: 'اضغط لرفع شعارك',
      text2: 'او قم بسحبها وافلاتها',
    },
    video: 'اضف فيديو تعريفي',
    program: [
      { value: 'برنامجي', label: 'برنامجي' },
      { value: 'برنامج مرشد', label: 'برنامج مرشد' },
      { value: 'برنامج مداد', label: 'برنامج مداد' },
      { value: 'برنامج الميتاك', label: 'برنامج الميتاك' },
      { value: 'برنامج مستقبلي', label: 'برنامج مستقبلي' },
      { value: 'برنامج اول خطواتي', label: 'برنامج اول خطواتي' },
      { value: 'برنامج النهار', label: 'برنامج النهار' },
      { value: 'برنامج دار اوسامة', label: 'برنامج دار اوسامة' },
      { value: 'برنامج المنصوري', label: 'برنامج المنصوري' },
      { value: 'برنامج القارئ الصغير', label: 'برنامج القارئ الصغير' },
      { value: 'برنامج جليس', label: 'برنامج جليس' },
      { value: 'برنامج اهلا', label: 'برنامج اهلا' },
      { value: 'اخرى', label: 'اخرى' },
    ],
    submit: 'اشتراك',
  },
};

export const wilaya = {
  en: {
    title: 'choose your wilaya',
    options: [
      { value: 'Alger', label: 'Alger' },
      { value: 'Oran', label: 'Oran' },
      { value: 'Constantine', label: 'Constantine' },
      { value: 'Annaba', label: 'Annaba' },
      { value: 'Batna', label: 'Batna' },
      { value: 'Bejaia', label: 'Bejaia' },
      { value: 'Biskra', label: 'Biskra' },
      { value: 'Blida', label: 'Blida' },
      { value: 'Bouira', label: 'Bouira' },
      { value: 'Boumerdes', label: 'Boumerdes' },
      { value: 'Chlef', label: 'Chlef' },
      { value: 'Djelfa', label: 'Djelfa' },
      { value: 'El Bayadh', label: 'El Bayadh' },
      { value: 'El Oued', label: 'El Oued' },
      { value: 'El Tarf', label: 'El Tarf' },
      { value: 'Ghardaia', label: 'Ghardaia' },
      { value: 'Guelma', label: 'Guelma' },
      { value: 'Illizi', label: 'Illizi' },
      { value: 'Jijel', label: 'Jijel' },
      { value: 'Khenchela', label: 'Khenchela' },
      { value: 'Laghouat', label: 'Laghouat' },
      { value: 'Mascara', label: 'Mascara' },
      { value: 'Medea', label: 'Medea' },
      { value: 'Mila', label: 'Mila' },
      { value: 'Mostaganem', label: 'Mostaganem' },
      { value: 'Msila', label: 'Msila' },
      { value: 'Naama', label: 'Naama' },
      { value: 'Oum El Bouaghi', label: 'Oum El Bouaghi' },
      { value: 'Relizane', label: 'Relizane' },
      { value: 'Saida', label: 'Saida' },
      { value: 'Setif', label: 'Setif' },
      { value: 'Sidi Bel Abbes', label: 'Sidi Bel Abbes' },
      { value: 'Skikda', label: 'Skikda' },
      { value: 'Souk Ahras', label: 'Souk Ahras' },
      { value: 'Tamanghasset', label: 'Tamanghasset' },
      { value: 'Tebessa', label: 'Tebessa' },
      { value: 'Tiaret', label: 'Tiaret' },
      { value: 'Tindouf', label: 'Tindouf' },
      { value: 'Tipaza', label: 'Tipaza' },
      { value: 'Tissemsilt', label: 'Tissemsilt' },
      { value: 'Tizi Ouzou', label: 'Tizi Ouzou' },
      { value: 'Tlemcen', label: 'Tlemcen' },
    ],
  },
  ar: {
    title: 'اختر ولايتك',
    options: [
      { value: 'alger', label: 'الجزائر' },
      { value: 'oran', label: 'وهران' },
      { value: 'constantine', label: 'قسنطينة' },
      { value: 'annaba', label: 'عنابة' },
      { value: 'batna', label: 'باتنة' },
      { value: 'bejaia', label: 'بجاية' },
      { value: 'biskra', label: 'بسكرة' },
      { value: 'blida', label: 'البليدة' },
      { value: 'bouira', label: 'بويرة' },
      { value: 'boumerdes', label: 'بومرداس' },
      { value: 'chlef', label: 'الشلف' },
      { value: 'djelfa', label: 'جلفة' },
      { value: 'el bayadh', label: 'البيض' },
      { value: 'el oued', label: 'الوادي' },
      { value: 'el tarf', label: 'الطارف' },
      { value: 'ghardaia', label: 'غرداية' },
      { value: 'guelma', label: 'قالمة' },
      { value: 'illizi', label: 'إليزي' },
      { value: 'jijel', label: 'جيجل' },
      { value: 'khenchela', label: 'خنشلة' },
      { value: 'laghouat', label: 'الأغواط' },
      { value: 'mascara', label: 'معسكر' },
      { value: 'medea', label: 'المدية' },
      { value: 'mila', label: 'ميلة' },
      { value: 'mostaganem', label: 'المستغانم' },
      { value: 'msila', label: 'مسيلة' },
      { value: 'naama', label: 'النعامة' },
      { value: 'oum el bouaghi', label: 'أم البواقي' },
      { value: 'relizane', label: 'الرياض' },
      { value: 'saida', label: 'سعيدة' },
      { value: 'setif', label: 'سطيف' },
      { value: 'sidi bel abbes', label: 'سيدي بلعباس' },
      { value: 'skikda', label: 'سكيكدة' },
      { value: 'souk ahras', label: 'سوق أهراس' },
      { value: 'tamanghasset', label: 'تمنغاست' },
      { value: 'tebessa', label: 'تبسة' },
      { value: 'tiaret', label: 'تيارت' },
      { value: 'tindouf', label: 'تندوف' },
      { value: 'tipaza', label: 'تيبازة' },
      { value: 'tissemsilt', label: 'تسمسيلت' },
      { value: 'tizi ouzou', label: 'تيزي وزو' },
      { value: 'tlemcen', label: 'تلمسان' },
    ],
  },
};
export const vendor = {
  en: {
    label: 'store label',
    logo: 'store logo',
    description: 'store description',
    filed: {
      title: 'choose your filed',
      options: [
        { value: 'Clothes', label: 'Clothes' },
        { value: 'Shoes', label: 'Shoes' },
        { value: 'Accessories', label: 'Accessories' },
        { value: 'Bags', label: 'Bags' },
        { value: 'Jewelry', label: 'Jewelry' },
        { value: 'Beauty', label: 'Beauty' },
        { value: 'Home', label: 'Home' },
        { value: 'Kids', label: 'Kids' },
        { value: 'Sport', label: 'Sport' },
        { value: 'Electronics', label: 'Electronics' },
        { value: 'Books', label: 'Books' },
        { value: 'Other', label: 'Other' },
      ],
    },
    phone: 'phone number',
    email: 'email',
    address: 'address',
    delivery: [
      { value: 'available', label: 'available' },
      { value: 'not available', label: 'not available' },
    ],
    submit: 'subscribe',
  },
  ar: {
    label: 'اسم المتجر',
    logo: 'شعار المتجر',
    description: 'وصف المتجر',
    filed: {
      title: 'اختر المجال',
      options: [
        { value: 'Clothes', label: 'ملابس' },
        { value: 'Shoes', label: 'أحذية' },
        { value: 'Accessories', label: 'إكسسوارات' },
        { value: 'Bags', label: 'حقائب' },
        { value: 'Jewelry', label: 'مجوهرات' },
        { value: 'Beauty', label: 'جمال' },
        { value: 'Home', label: 'منزل' },
        { value: 'Kids', label: 'أطفال' },
        { value: 'Sport', label: 'رياضة' },
        { value: 'Electronics', label: 'إلكترونيات' },
        { value: 'Books', label: 'كتب' },
        { value: 'Other', label: 'أخرى' },
      ],
    },
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    delivery: [
      { value: 'available', label: 'متوفر' },
      { value: 'not available', label: 'غير متوفر' },
    ],
    submit: 'اشتراك',
  },
};

export const user = {
  en: {
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    type: {
      title: 'are you a:',
      options: [
        { value: 'Kindergarten manager', label: 'Kindergarten manager' },
        { value: 'Kindergarten teacher', label: 'Kindergarten teacher' },
        { value: 'parent', label: 'parent' },
        { value: 'worker', label: 'worker in a kindergarten' },
        { value: 'other', label: 'other' },
      ],
    },
    phone: 'Phone',
    facebook: 'Facebook',
    submit: 'subscribe',
  },
  ar: {
    firstName: 'الاسم الاول',
    lastName: 'الاسم الاخير',
    email: 'البريد الالكتروني',
    type: {
      title: 'هل انت:',
      options: [
        { value: 'Kindergarten manager', label: 'مدير حضانة' },
        { value: 'Kindergarten teacher', label: 'معلم حضانة' },
        { value: 'parent', label: 'والد' },
        { value: 'worker', label: 'عامل في حضانة' },
        { value: 'other', label: 'اخرى' },
      ],
    },
    phone: 'رقم الهاتف',
    facebook: 'فيسبوك',
    submit: 'اشتراك',
  },
};

export const country = {
  en: {
    title: 'choose your country',
    options: [
      { label: 'Afghanistan', value: 'AF' },
      { label: 'Åland Islands', value: 'AX' },
      { label: 'Albania', value: 'AL' },
      { label: 'Algeria', value: 'DZ' },
      { label: 'American Samoa', value: 'AS' },
      { label: 'AndorrA', value: 'AD' },
      { label: 'Angola', value: 'AO' },
      { label: 'Anguilla', value: 'AI' },
      { label: 'Antarctica', value: 'AQ' },
      { label: 'Antigua and Barbuda', value: 'AG' },
      { label: 'Argentina', value: 'AR' },
      { label: 'Armenia', value: 'AM' },
      { label: 'Aruba', value: 'AW' },
      { label: 'Australia', value: 'AU' },
      { label: 'Austria', value: 'AT' },
      { label: 'Azerbaijan', value: 'AZ' },
      { label: 'Bahamas', value: 'BS' },
      { label: 'Bahrain', value: 'BH' },
      { label: 'Bangladesh', value: 'BD' },
      { label: 'Barbados', value: 'BB' },
      { label: 'Belarus', value: 'BY' },
      { label: 'Belgium', value: 'BE' },
      { label: 'Belize', value: 'BZ' },
      { label: 'Benin', value: 'BJ' },
      { label: 'Bermuda', value: 'BM' },
      { label: 'Bhutan', value: 'BT' },
      { label: 'Bolivia', value: 'BO' },
      { label: 'Bosnia and Herzegovina', value: 'BA' },
      { label: 'Botswana', value: 'BW' },
      { label: 'Bouvet Island', value: 'BV' },
      { label: 'Brazil', value: 'BR' },
      { label: 'British Indian Ocean Territory', value: 'IO' },
      { label: 'Brunei Darussalam', value: 'BN' },
      { label: 'Bulgaria', value: 'BG' },
      { label: 'Burkina Faso', value: 'BF' },
      { label: 'Burundi', value: 'BI' },
      { label: 'Cambodia', value: 'KH' },
      { label: 'Cameroon', value: 'CM' },
      { label: 'Canada', value: 'CA' },
      { label: 'Cape Verde', value: 'CV' },
      { label: 'Cayman Islands', value: 'KY' },
      { label: 'Central African Republic', value: 'CF' },
      { label: 'Chad', value: 'TD' },
      { label: 'Chile', value: 'CL' },
      { label: 'China', value: 'CN' },
      { label: 'Christmas Island', value: 'CX' },
      { label: 'Cocos (Keeling) Islands', value: 'CC' },
      { label: 'Colombia', value: 'CO' },
      { label: 'Comoros', value: 'KM' },
      { label: 'Congo', value: 'CG' },
      { label: 'Congo, The Democratic Republic of the', value: 'CD' },
      { label: 'Cook Islands', value: 'CK' },
      { label: 'Costa Rica', value: 'CR' },
      { label: "Cote D'Ivoire", value: 'CI' },
      { label: 'Croatia', value: 'HR' },
      { label: 'Cuba', value: 'CU' },
      { label: 'Cyprus', value: 'CY' },
      { label: 'Czech Republic', value: 'CZ' },
      { label: 'Denmark', value: 'DK' },
      { label: 'Djibouti', value: 'DJ' },
      { label: 'Dominica', value: 'DM' },
      { label: 'Dominican Republic', value: 'DO' },
      { label: 'Ecuador', value: 'EC' },
      { label: 'Egypt', value: 'EG' },
      { label: 'El Salvador', value: 'SV' },
      { label: 'Equatorial Guinea', value: 'GQ' },
      { label: 'Eritrea', value: 'ER' },
      { label: 'Estonia', value: 'EE' },
      { label: 'Ethiopia', value: 'ET' },
      { label: 'Falkland Islands (Malvinas)', value: 'FK' },
      { label: 'Faroe Islands', value: 'FO' },
      { label: 'Fiji', value: 'FJ' },
      { label: 'Finland', value: 'FI' },
      { label: 'France', value: 'FR' },
      { label: 'French Guiana', value: 'GF' },
      { label: 'French Polynesia', value: 'PF' },
      { label: 'French Southern Territories', value: 'TF' },
      { label: 'Gabon', value: 'GA' },
      { label: 'Gambia', value: 'GM' },
      { label: 'Georgia', value: 'GE' },
      { label: 'Germany', value: 'DE' },
      { label: 'Ghana', value: 'GH' },
      { label: 'Gibraltar', value: 'GI' },
      { label: 'Greece', value: 'GR' },
      { label: 'Greenland', value: 'GL' },
      { label: 'Grenada', value: 'GD' },
      { label: 'Guadeloupe', value: 'GP' },
      { label: 'Guam', value: 'GU' },
      { label: 'Guatemala', value: 'GT' },
      { label: 'Guernsey', value: 'GG' },
      { label: 'Guinea', value: 'GN' },
      { label: 'Guinea-Bissau', value: 'GW' },
      { label: 'Guyana', value: 'GY' },
      { label: 'Haiti', value: 'HT' },
      { label: 'Heard Island and Mcdonald Islands', value: 'HM' },
      { label: 'Holy See (Vatican City State)', value: 'VA' },
      { label: 'Honduras', value: 'HN' },
      { label: 'Hong Kong', value: 'HK' },
      { label: 'Hungary', value: 'HU' },
      { label: 'Iceland', value: 'IS' },
      { label: 'India', value: 'IN' },
      { label: 'Indonesia', value: 'ID' },
      { label: 'Iran, Islamic Republic Of', value: 'IR' },
      { label: 'Iraq', value: 'IQ' },
      { label: 'Ireland', value: 'IE' },
      { label: 'Isle of Man', value: 'IM' },
      { label: 'Israel', value: 'IL' },
      { label: 'Italy', value: 'IT' },
      { label: 'Jamaica', value: 'JM' },
      { label: 'Japan', value: 'JP' },
      { label: 'Jersey', value: 'JE' },
      { label: 'Jordan', value: 'JO' },
      { label: 'Kazakhstan', value: 'KZ' },
      { label: 'Kenya', value: 'KE' },
      { label: 'Kiribati', value: 'KI' },
      { label: "Korea, Democratic People'S Republic of", value: 'KP' },
      { label: 'Korea, Republic of', value: 'KR' },
      { label: 'Kuwait', value: 'KW' },
      { label: 'Kyrgyzstan', value: 'KG' },
      { label: "Lao People'S Democratic Republic", value: 'LA' },
      { label: 'Latvia', value: 'LV' },
      { label: 'Lebanon', value: 'LB' },
      { label: 'Lesotho', value: 'LS' },
      { label: 'Liberia', value: 'LR' },
      { label: 'Libyan Arab Jamahiriya', value: 'LY' },
      { label: 'Liechtenstein', value: 'LI' },
      { label: 'Lithuania', value: 'LT' },
      { label: 'Luxembourg', value: 'LU' },
      { label: 'Macao', value: 'MO' },
      { label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK' },
      { label: 'Madagascar', value: 'MG' },
      { label: 'Malawi', value: 'MW' },
      { label: 'Malaysia', value: 'MY' },
      { label: 'Maldives', value: 'MV' },
      { label: 'Mali', value: 'ML' },
      { label: 'Malta', value: 'MT' },
      { label: 'Marshall Islands', value: 'MH' },
      { label: 'Martinique', value: 'MQ' },
      { label: 'Mauritania', value: 'MR' },
      { label: 'Mauritius', value: 'MU' },
      { label: 'Mayotte', value: 'YT' },
      { label: 'Mexico', value: 'MX' },
      { label: 'Micronesia, Federated States of', value: 'FM' },
      { label: 'Moldova, Republic of', value: 'MD' },
      { label: 'Monaco', value: 'MC' },
      { label: 'Mongolia', value: 'MN' },
      { label: 'Montserrat', value: 'MS' },
      { label: 'Morocco', value: 'MA' },
      { label: 'Mozambique', value: 'MZ' },
      { label: 'Myanmar', value: 'MM' },
      { label: 'Namibia', value: 'NA' },
      { label: 'Nauru', value: 'NR' },
      { label: 'Nepal', value: 'NP' },
      { label: 'Netherlands', value: 'NL' },
      { label: 'Netherlands Antilles', value: 'AN' },
      { label: 'New Caledonia', value: 'NC' },
      { label: 'New Zealand', value: 'NZ' },
      { label: 'Nicaragua', value: 'NI' },
      { label: 'Niger', value: 'NE' },
      { label: 'Nigeria', value: 'NG' },
      { label: 'Niue', value: 'NU' },
      { label: 'Norfolk Island', value: 'NF' },
      { label: 'Northern Mariana Islands', value: 'MP' },
      { label: 'Norway', value: 'NO' },
      { label: 'Oman', value: 'OM' },
      { label: 'Pakistan', value: 'PK' },
      { label: 'Palau', value: 'PW' },
      { label: 'Palestinian Territory, Occupied', value: 'PS' },
      { label: 'Panama', value: 'PA' },
      { label: 'Papua New Guinea', value: 'PG' },
      { label: 'Paraguay', value: 'PY' },
      { label: 'Peru', value: 'PE' },
      { label: 'Philippines', value: 'PH' },
      { label: 'Pitcairn', value: 'PN' },
      { label: 'Poland', value: 'PL' },
      { label: 'Portugal', value: 'PT' },
      { label: 'Puerto Rico', value: 'PR' },
      { label: 'Qatar', value: 'QA' },
      { label: 'Reunion', value: 'RE' },
      { label: 'Romania', value: 'RO' },
      { label: 'Russian Federation', value: 'RU' },
      { label: 'RWANDA', value: 'RW' },
      { label: 'Saint Helena', value: 'SH' },
      { label: 'Saint Kitts and Nevis', value: 'KN' },
      { label: 'Saint Lucia', value: 'LC' },
      { label: 'Saint Pierre and Miquelon', value: 'PM' },
      { label: 'Saint Vincent and the Grenadines', value: 'VC' },
      { label: 'Samoa', value: 'WS' },
      { label: 'San Marino', value: 'SM' },
      { label: 'Sao Tome and Principe', value: 'ST' },
      { label: 'Saudi Arabia', value: 'SA' },
      { label: 'Senegal', value: 'SN' },
      { label: 'Serbia and Montenegro', value: 'CS' },
      { label: 'Seychelles', value: 'SC' },
      { label: 'Sierra Leone', value: 'SL' },
      { label: 'Singapore', value: 'SG' },
      { label: 'Slovakia', value: 'SK' },
      { label: 'Slovenia', value: 'SI' },
      { label: 'Solomon Islands', value: 'SB' },
      { label: 'Somalia', value: 'SO' },
      { label: 'South Africa', value: 'ZA' },
      { label: 'South Georgia and the South Sandwich Islands', value: 'GS' },
      { label: 'Spain', value: 'ES' },
      { label: 'Sri Lanka', value: 'LK' },
      { label: 'Sudan', value: 'SD' },
      { label: 'Surilabel', value: 'SR' },
      { label: 'Svalbard and Jan Mayen', value: 'SJ' },
      { label: 'Swaziland', value: 'SZ' },
      { label: 'Sweden', value: 'SE' },
      { label: 'Switzerland', value: 'CH' },
      { label: 'Syrian Arab Republic', value: 'SY' },
      { label: 'Taiwan, Province of China', value: 'TW' },
      { label: 'Tajikistan', value: 'TJ' },
      { label: 'Tanzania, United Republic of', value: 'TZ' },
      { label: 'Thailand', value: 'TH' },
      { label: 'Timor-Leste', value: 'TL' },
      { label: 'Togo', value: 'TG' },
      { label: 'Tokelau', value: 'TK' },
      { label: 'Tonga', value: 'TO' },
      { label: 'Trinidad and Tobago', value: 'TT' },
      { label: 'Tunisia', value: 'TN' },
      { label: 'Turkey', value: 'TR' },
      { label: 'Turkmenistan', value: 'TM' },
      { label: 'Turks and Caicos Islands', value: 'TC' },
      { label: 'Tuvalu', value: 'TV' },
      { label: 'Uganda', value: 'UG' },
      { label: 'Ukraine', value: 'UA' },
      { label: 'United Arab Emirates', value: 'AE' },
      { label: 'United Kingdom', value: 'GB' },
      { label: 'United States', value: 'US' },
      { label: 'United States Minor Outlying Islands', value: 'UM' },
      { label: 'Uruguay', value: 'UY' },
      { label: 'Uzbekistan', value: 'UZ' },
      { label: 'Vanuatu', value: 'VU' },
      { label: 'Venezuela', value: 'VE' },
      { label: 'Viet Nam', value: 'VN' },
      { label: 'Virgin Islands, British', value: 'VG' },
      { label: 'Virgin Islands, U.S.', value: 'VI' },
      { label: 'Wallis and Futuna', value: 'WF' },
      { label: 'Western Sahara', value: 'EH' },
      { label: 'Yemen', value: 'YE' },
      { label: 'Zambia', value: 'ZM' },
      { label: 'Zimbabwe', value: 'ZW' },
    ],
  },
};

export const loginForm = {
  en: {
    title: 'Welcome back to ',
    header: 'Login to your account',
    phone: {
      label: 'Phone number',
      placeholder: 'Enter your phone number',
    },
    password: {
      label: 'Password',
      placeholder: 'Enter your password',
    },
    forgotPassword: 'Forgot password?',
    login: 'Login',
    register: 'Register',
    login: 'Login',
    dontHaveAccount: 'Don’t have an account yet ?',
    register: 'sign up',
  },
  ar: {
    title: 'مرحبا بعودتك إلى ',
    header: 'تسجيل الدخول إلى حسابك',
    phone: {
      label: 'رقم الهاتف',
      placeholder: 'أدخل رقم هاتفك',
    },
    password: {
      label: 'كلمة المرور',
      placeholder: 'أدخل كلمة المرور الخاصة بك',
    },
    forgotPassword: 'هل نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    login: 'تسجيل الدخول',
    dontHaveAccount: 'ليس لديك حساب بعد؟',
    register: 'سجل الآن',
  },
};

export const loginModel = {
  en: {
    create: 'Create Post',
    username: 'User name',
    textArea: 'what is in your mind?',
    post: 'Post',
    privacy: [
      { label: 'Public', value: 'public' },
      { label: 'Onlyme', value: 'onlyme' },
      { label: 'kindergatens Only', value: 'kindergatens' },
    ],
    post: 'Post',
  },
  ar: {
    create: 'إنشاء منشور',
    username: 'اسم المستخدم',
    textArea: 'ماذا في بالك؟',
    post: 'نشر',
    privacy: [
      { label: 'عام', value: 'public' },
      { label: 'فقط لي', value: 'onlyme' },
      { label: 'الروضات فقط', value: 'kindergatens' },
    ],
    post: 'نشر',
  },
};

export const posts = [
  {
    id: 1,
    user: 'radwdati.dz',
    comments: 4,
    tags: ['KIDS', 'PLAY AREA', 'PLAYGROUNDS'],
    title: 'Why are Playgrounds Important for Kids',
    date: moment(new Date()).format('dddd, MMMM Do YYYY'),
    content: {
      subContent:
        'Holistically pontificate installed base portals after maintainable products. Phosfluorescently engage worldwide methodologies with technology. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.',
      fullContent:
        'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service. Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables. Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.',
    },
    image:
      'https://bambino.bold-themes-cdn.com/demo-01/wp-content/uploads/sites/2/2022/03/post_12.jpg',
  },
  {
    id: 2,
    user: 'radwdati.dz',
    comments: 4,
    tags: ['ACTIVITIES', 'GAMES'],
    title: 'Why are Playgrounds Important for Kids',
    date: moment(new Date()).format('dddd, MMMM Do YYYY'),
    content: {
      subContent:
        'Holistically pontificate installed base portals after maintainable products. Phosfluorescently engage worldwide methodologies with technology. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.',
      fullContent:
        'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service. Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables. Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.',
    },
    image:
      'https://bambino.bold-themes-cdn.com/demo-01/wp-content/uploads/sites/2/2022/03/post_11-1280x640.jpg',
  },
  {
    id: 3,
    user: 'radwdati.dz',
    comments: 4,
    tags: ['GAMES', 'KIDS'],
    title: 'Why are Playgrounds Important for Kids',
    date: moment(new Date()).format('dddd, MMMM Do YYYY'),
    content: {
      subContent:
        'Holistically pontificate installed base portals after maintainable products. Phosfluorescently engage worldwide methodologies with technology. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.',
      fullContent:
        'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service. Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables. Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.',
    },
    image:
      'https://bambino.bold-themes-cdn.com/demo-01/wp-content/uploads/sites/2/2018/09/post_02-1280x640.jpg',
  },
  {
    id: 4,
    user: 'radwdati.dz',
    comments: 4,
    tags: ['KIDS', 'PLAY AREA'],
    title: 'Why are Playgrounds Important for Kids',
    date: moment(new Date()).format('dddd, MMMM Do YYYY'),
    content: {
      subContent:
        'Holistically pontificate installed base portals after maintainable products. Phosfluorescently engage worldwide methodologies with technology. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.',
      fullContent:
        'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service. Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables. Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.',
    },
    image:
      'https://bambino.bold-themes-cdn.com/demo-01/wp-content/uploads/sites/2/2018/09/post_03.jpg',
  },
  {
    id: 5,
    user: 'radwdati.dz',
    comments: 4,
    tags: ['KIDS', 'PLAY AREA'],
    title: 'Why are Playgrounds Important for Kids',
    date: moment(new Date()).format('dddd, MMMM Do YYYY'),
    content: {
      subContent:
        'Holistically pontificate installed base portals after maintainable products. Phosfluorescently engage worldwide methodologies with technology. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI.',
      fullContent:
        'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line. Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI. Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service. Objectively innovate empowered manufactured products whereas parallel platforms. Holisticly predominate extensible testing procedures for reliable supply chains. Dramatically engage top-line web services vis-a-vis cutting-edge deliverables. Proactively envisioned multimedia based expertise and cross-media growth strategies. Seamlessly visualize quality intellectual capital without superior collaboration and idea-sharing. Holistically pontificate installed base portals after maintainable products.',
    },
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4nm8_JC0gHglGu70bS0gbnYQ5JOhL4sdeJA&usqp=CAU',
  },
];
export const categories = {
  en: [
    { value: 'activities', label: 'Activities' },
    { value: 'games', label: 'Games' },
    { value: 'kids', label: 'Kids' },
    { value: 'play area', label: 'Play Area' },
    { value: 'playgrounds', label: 'Playgrounds' },
    { value: 'toys', label: 'Toys' },
    { value: 'toys for kids', label: 'Toys for Kids' },
  ],
  ar: [
    { value: 'activities', label: 'الأنشطة' },
    { value: 'games', label: 'الألعاب' },
    { value: 'kids', label: 'الأطفال' },
    { value: 'play area', label: 'منطقة اللعب' },
    { value: 'playgrounds', label: 'ملاعب اللعب' },
    { value: 'toys', label: 'اللعب' },
    { value: 'toys for kids', label: 'لعب للأطفال' },
  ],
};
